version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./.env
    ports:
      - "3000:3000"

volumes:
  postgres_data: